migrate lake-relay from go to rust

diff --git a/dev/lifecycle/documentation b/dev/lifecycle/documentation
--- a/dev/lifecycle/documentation
+++ b/dev/lifecycle/documentation
@@ -6,11 +6,13 @@ trap exit INT TERM
 ################################################################################
 
 SOURCE=""
+OUTPUT=""
 while [ $# -gt 0 ] ; do
 key="$1"
 case $key in
-  --source)  SOURCE="$2";  shift; shift; ;;
-  *)                       shift;        ;;
+  --source) SOURCE="$2";  shift; shift; ;;
+  --output) OUTPUT="$2";  shift; shift; ;;
+  *)                      shift;        ;;
 esac
 done
 
@@ -21,29 +23,37 @@ if [ -z "${SOURCE}" ] ; then
   exit 1
 fi
 
+if [ -z "${OUTPUT}" ] ; then
+  (>&2 echo "[error] output not provided")
+  exit 1
+fi
+
 ################################################################################
 
-lifecycle::rust::lint() {
+lifecycle::rus::doc() {
   local dir="$1"
   if [ -z ${dir} -o ! -d ${dir} ] ; then
     return
   fi
+  local output="$2"
 
-  cd $dir && \
-  CARGO_HOME=${dir}/target \
-  cargo fmt
+  (rm -rf ${dir}/target/doc 2> /dev/null || :)
+  mkdir -p ${output}
+  (rm -rf ${output}/* 2> /dev/null || :)
 
-  cd $dir && \
+  cd ${dir} && \
   CARGO_HOME=${dir}/target \
   CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=clang-13 \
   CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=clang-13 \
-  cargo clippy \
-    -- \
-    -D warnings \
-    -W clippy::pedantic
+  cargo doc \
+    --all-features \
+    --no-deps \
+    --workspace
+  (cd ${dir}/target/doc && tar c .) | (cd ${output} && tar xf -)
 }
 
 ################################################################################
 
-lifecycle::rust::lint \
-  ${SOURCE}
+lifecycle::rus::doc \
+  ${SOURCE} \
+  ${OUTPUT}
