better project structure and more robust testing, minor quality of life improvements

diff --git a/dev/lifecycle/package b/dev/lifecycle/package
--- a/dev/lifecycle/package
+++ b/dev/lifecycle/package
@@ -3,18 +3,25 @@
 set -eu
 trap exit INT TERM
 
-dist="packaging/bin"
-target="linux/amd64"
+TARGET_ARCHITECTURE="linux/amd64"
+TARGET_PACKAGE=""
 
 package_service() {
-  local arch=${2#*/}
-  local platform=${2%%/*}
-  local output=${1}/${platform}-${arch}
+  local working_dir=/go/src/github.com/jancajthaml-openbank/${TARGET_PACKAGE}
+  local arch=${TARGET_ARCHITECTURE#*/}
+  local platform=${TARGET_ARCHITECTURE%%/*}
+  local output=$(pwd)/packaging/bin/${TARGET_PACKAGE}-${platform}-${arch}
+
   if [ -f ${output} ] ; then
     rm -f ${output}
   fi
 
-  echo "[info] packaging for ${platform}/${arch}"
+  cd ${working_dir}
+
+  echo "[info] cleaning"
+  go clean
+
+  echo "[info] packaging ${TARGET_PACKAGE} for ${platform}/${arch}"
 
   case ${arch} in
 
@@ -26,10 +33,9 @@ package_service() {
       CGO_ENABLED=1 \
       \
       go build -a -o ${output} || {
-        (>&2 echo "unable to build for ${platform}/armhf")
+        (>&2 echo "[error] unable to build for ${platform}/armhf")
         exit 1
       }
-      file ${output}
     ;;
 
     amd64)
@@ -39,20 +45,20 @@ package_service() {
       CGO_ENABLED=1 \
       \
       go build -a -o ${output} || {
-        (>&2 echo "unable to build for ${platform}/amd64")
+        (>&2 echo "[error] unable to build for ${platform}/amd64")
         exit 1
       }
-      file ${output}
     ;;
 
     *)
-      (>&2 echo "unsupported target ${platform}/${arch}")
+      (>&2 echo "[error] unsupported target ${platform}/${arch}")
       exit 1
     ;;
 
   esac
 
   chmod +x ${output}
+  file ${output}
 }
 
 while [ $# -gt 0 ] ; do
@@ -60,14 +66,14 @@ key="$1"
 
 case $key in
 
-  --target)
-    target="$2"
+  --arch)
+    TARGET_ARCHITECTURE="$2"
     shift
     shift
   ;;
 
-  -o|--output)
-    dist="$2"
+  --pkg)
+    TARGET_PACKAGE="$2"
     shift
     shift
   ;;
@@ -79,9 +85,11 @@ case $key in
 esac
 done
 
-echo "[info] cleaning"
-go clean
+if [ ! "${TARGET_PACKAGE}" ] ; then
+  (>&2 echo "[error] target package not provided")
+  exit 1
+fi
 
-package_service ${dist} ${target}
+package_service
 
 echo "[info] done"
diff --git a/dev/lifecycle/release b/dev/lifecycle/release
--- a/dev/lifecycle/release
+++ b/dev/lifecycle/release
@@ -10,35 +10,39 @@ while [ $# -gt 0 ] ; do
 key="$1"
 
 case $key in
-    -v|--version)
+
+  -v|--version)
     VERSION="$2"
     shift
     shift
-    ;;
-    -t|--token)
+  ;;
+
+  -t|--token)
     ACCESS_TOKEN="$2"
     shift
     shift
-    ;;
-    *)
+  ;;
+
+  *)
     shift
-    ;;
+  ;;
+
 esac
 done
 
 if [ ! "${VERSION}" ] ; then
-  (>&2 echo "version not provided")
+  (>&2 echo "[error] version not provided")
   exit 1
 fi
 
 if [ ! "${ACCESS_TOKEN}" ] ; then
-  (>&2 echo "github access token not provided")
+  (>&2 echo "[error] github access token not provided")
   exit 1
 fi
 
-REPO=jancajthaml-openbank/lake
+REPO=jancajthaml-openbank/fio-bco
 
-echo "start release of ${REPO}:${VERSION} "
+echo "[info] start release of ${REPO}:${VERSION} "
 
 RELEASE_INFO="https://api.github.com/repos/${REPO}/releases/tags/${VERSION}"
 response=$(curl \
@@ -51,10 +55,10 @@ RELEASE_ID=$(echo "$response" | jq -r .id)
 RELEASE_URI="https://api.github.com/repos/${REPO}/releases"
 
 if [ "${RELEASE_ID}" != "null" ] ; then
-  (>&2 echo "release ${VERSION} already exists")
+  (>&2 echo "[error] release ${VERSION} already exists")
   exit 1
 else
-  echo "creating new release ${VERSION}"
+  echo "[info] creating new release ${VERSION}"
 fi
 
 PAYLOAD=$(cat <<-END
@@ -79,23 +83,23 @@ response=$(
     ${RELEASE_URI}
 )
 
-UPLOAD_URL=$(echo $response | jq -r .upload_url | sed -e "s/{?name,label}//")
+UPLOAD_URL=$(echo ${response} | jq -r .upload_url | sed -e "s/{?name,label}//")
 
-assets_dir=packaging/bin
+assets_dir=$(pwd)/packaging/bin
 
 for asset in $(ls -1 packaging/bin); do
   abspath="${assets_dir}/${asset}"
 
-  if [ ! -f $abspath ] ; then
-    (>&2 echo "asset ${abspath} not found")
+  if [ ! -f ${abspath} ] ; then
+    (>&2 echo "[error] asset ${abspath} not found")
     exit 1
   fi
 
-  echo "uploading $asset"
+  echo "[info] uploading ${asset}"
 
   curl \
     --fail \
-    --request POST \
+    -X POST \
     -# \
     --output /dev/null \
     --data-binary "@${abspath}" \
@@ -104,4 +108,4 @@ for asset in $(ls -1 packaging/bin); do
     "${UPLOAD_URL}?name=${asset}"
 done
 
-echo "released ${VERSION}"
+echo "[info] released ${VERSION}"
