wip (#55)
* rework of circleci pipeline
* only release one binary per platform, no copying

diff --git a/dev/lifecycle/release b/dev/lifecycle/release
--- a/dev/lifecycle/release
+++ b/dev/lifecycle/release
@@ -1,12 +1,12 @@
-#!/bin/bash
+#!/bin/sh
 
-set -Eeuo pipefail
+set -eu
 trap exit INT TERM
 
 VERSION=""
 ACCESS_TOKEN=""
 
-while [[ $# -gt 0 ]] ; do
+while [ $# -gt 0 ] ; do
 key="$1"
 
 case $key in
@@ -26,17 +26,19 @@ case $key in
 esac
 done
 
-if [ -z "${VERSION// }" ] ; then
-  echo "version not provided"
+if [ ! "${VERSION}" ] ; then
+  (>&2 echo "version not provided")
   exit 1
 fi
 
-if [ -z "${ACCESS_TOKEN// }" ] ; then
-  echo "github access token not provided"
+if [ ! "${ACCESS_TOKEN}" ] ; then
+  (>&2 echo "github access token not provided")
   exit 1
 fi
 
 REPO=jancajthaml-openbank/lake
+
+echo "start release of ${REPO}:${VERSION} "
 
 RELEASE_INFO="https://api.github.com/repos/${REPO}/releases/tags/${VERSION}"
 response=$(curl \
@@ -45,14 +47,14 @@ response=$(curl \
     ${RELEASE_INFO} \
 )
 
-RELEASE_ID=$(jq -r .id <<< "$response")
+RELEASE_ID=$(echo "$response" | jq -r .id)
 RELEASE_URI="https://api.github.com/repos/${REPO}/releases"
 
 if [ "${RELEASE_ID}" != "null" ] ; then
-  echo "release ${VERSION} already exists"
+  (>&2 echo "release ${VERSION} already exists")
   exit 1
 else
-  echo "creating release ${VERSION}"
+  echo "creating new release ${VERSION}"
 fi
 
 PAYLOAD=$(cat <<-END
@@ -77,34 +79,29 @@ response=$(
     ${RELEASE_URI}
 )
 
-UPLOAD_URL=$(jq -r .upload_url <<< $response | sed -e "s/{?name,label}//")
+UPLOAD_URL=$(echo $response | jq -r .upload_url | sed -e "s/{?name,label}//")
 
-assets=(
-  "packaging/bin/lake_1.0.0_amd64.deb"
-  "packaging/bin/linux-amd64"
-)
+assets_dir=packaging/bin
 
-for asset in "${assets[@]}" ; do
-  if [ ! -f $asset ] ; then
-    echo "asset $asset not found"
+for asset in $(ls -1 packaging/bin); do
+  abspath="${assets_dir}/${asset}"
+
+  if [ ! -f $abspath ] ; then
+    (>&2 echo "asset ${abspath} not found")
     exit 1
   fi
 
-  label=$(basename $asset)
-
-  echo "uploading $label"
+  echo "uploading $asset"
 
   curl \
     --fail \
     --request POST \
     -# \
     --output /dev/null \
-    --data-binary "@${asset}" \
+    --data-binary "@${abspath}" \
     -H "Authorization: token $ACCESS_TOKEN" \
     -H "Content-Type: application/binary" \
-    "${UPLOAD_URL}?name=${label}"
+    "${UPLOAD_URL}?name=${asset}"
 done
 
 echo "released ${VERSION}"
-
-#https://github.com/jancajthaml-openbank/lake/releases/download/v1.2.3/lake_1.0.0_amd64.deb
