blocking zmqRecv and other demo finding fixes (#59)

diff --git a/packaging/debian_amd64/DEBIAN/postinst b/packaging/debian_amd64/DEBIAN/postinst
--- a/packaging/debian_amd64/DEBIAN/postinst
+++ b/packaging/debian_amd64/DEBIAN/postinst
@@ -1,29 +1,29 @@
-#!/bin/bash
+#!/bin/sh
 
 set -e
 
 case "$1" in
 
-    configure)
-        if [ -f "/etc/init/lake.conf" ] ; then
-            echo "Loading /etc/init/lake.conf"
-            . /etc/init/lake.conf
-            
-            systemctl unmask lake.service >/dev/null
-            systemctl enable lake.service >/dev/null
-        else
-            (>&2 echo "/etc/init/lake.conf file not found")
-            exit 1
-        fi
-    ;;
+  configure)
+    if [ -f "/etc/init/lake.conf" ] ; then
+      echo "Loading /etc/init/lake.conf"
+      . /etc/init/lake.conf
 
-    abort-upgrade|abort-remove|abort-deconfigure)
-    ;;
+      systemctl unmask lake.service >/dev/null
+      systemctl enable lake.service >/dev/null
+    else
+      (>&2 echo "/etc/init/lake.conf file not found")
+      exit 1
+    fi
+  ;;
 
-    *)
-        (>&2 echo "postinst called with unknown argument \ `$1`")
-        exit 1
-    ;;
+  abort-upgrade|abort-remove|abort-deconfigure)
+  ;;
+
+  *)
+    (>&2 echo "postinst called with unknown argument \ `$1`")
+    exit 1
+  ;;
 
 esac
 
